### ISSUE TITLE
ERROR: (NetworkError) Unable to publish contract - no explorer plugin installed. [APE-871]

### ISSUE THREAD

**Issue by PatrickAlphaC** [ApeWorX/ape-etherscan#85]
I have the etherscan explorer plugin installed, but it won't verify my sepolia contract. 

`FundMe` is a vyper contract. 

### Environment information

- `ape` and plugin versions:

```
$ ape --version
0.6.8

$ ape plugins list
  etherscan    0.6.3
  alchemy      0.6.1
  vyper        0.6.3
```

- Python Version: Python 3.10.6
- OS: macOS

### What went wrong?

I tried to verify my contract with a few methods and was unable.

Option 1:
```python
def deploy_fund_me(unlock_password=None) -> project.FundMe:
    account = get_account(unlock_password=unlock_password)
    fund_me = account.deploy(
        project.FundMe,
        price_feed.address,
        publish=true,
        sender=account
    )
    print(f"Contract deployed to {fund_me.address}")
    return fund_me
```

Output:
```bash
INFO: Submitted 0xeff951ff350153fba20a66406295815c1c2d5e151d9830c5a2fde0b996666ebc
Confirmations (2/2): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:28<00:00, 14.19s/it]
INFO: Confirmed 0xeff951ff350153fba20a66406295815c1c2d5e151d9830c5a2fde0b996666ebc (total fees paid = 321734002252138)
SUCCESS: Contract 'FundMe' deployed to: 0x0c16776abAb544dfAD30b411c21212121CBb8aEA

  File "/xxxx/scripts/deploy_fund_me.py", line 26, in main
    deploy_fund_me()
  File "/xxxxx/scripts/deploy_fund_me.py", line 15, in deploy_fund_me
    fund_me = account.deploy(

ERROR: (NetworkError) Unable to publish contract - no explorer plugin installed.
```

Option 2:
```bash
from ape import networks
>>> etherscan = networks.provider.network.explorer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxxx/ape/utils/basemodel.py", line 72, in provider
    raise ProviderNotConnectedError()
ape.exceptions.ProviderNotConnectedError: Not connected to a network provider.
```

Please include information like:

- what command you ran
```
ape run scripts/deploy_fund_me.py --network ethereum:sepolia:alchemy
```

**Comment by PatrickAlphaC** [comment]
Also attempted with:

```
ape console --network :sepolia
```

**Comment by antazoey** [comment]
this is fixed in ape-etherscan but we never released.
i can go ahead and do that now.
then switch to 0.6.4, ok? thx
